<%@ include file="../../tiles/templates/taglibs.jsp"%>

<!-- JSTREE -->
<link rel="stylesheet" href="/static/css/jstree/style.min.css" />
<script src="/static/js/jstree/jstree.js"></script>

<!-- Graphic generation JS -->
<script src="/static/js/productGraphics.js"></script>

<!-- This page's functions and global variables -->
<script>
var chart;
var selectedVp = ${ productSize };
var totalVp = ${ totalFeatures };
var treeData;
var chartLabel;

function calculate(selected) {
	return ((selected / parseFloat(totalVp)) * 100).toFixed(1) + " %";
}

function sunburstGoTo(id){
  //var item = treeData.search("id", id);

  // drill down to the item
  chart.drillTo(id);
}

var zoomFactor = 1.1;
var zooms = 0;
var zoomMax = 10;

function zoomIn(){
  if(zooms < zoomMax){
    $('#zoomOut').removeClass('disabled')
    $("#detailedGraphic").width($("#detailedGraphic").width() * zoomFactor);
    $("#detailedGraphic").height($("#detailedGraphic").height() * zoomFactor);
    chart.innerRadius(chart.innerRadius() * zoomFactor);
    zooms++;
    if(zooms == zoomMax)
      $('#zoomIn').addClass('disabled')
  }else{
    $('#zoomIn').addClass('disabled')
  }
}

function zoomOut(){
  if(zooms > 0){
    $('#zoomIn').removeClass('disabled')
    $("#detailedGraphic").width($("#detailedGraphic").width() / zoomFactor);
    $("#detailedGraphic").height($("#detailedGraphic").height() / zoomFactor);
    chart.innerRadius(chart.innerRadius() / zoomFactor);
    zooms--;
    if(zooms == 0)
      $('#zoomOut').addClass('disabled')
  }else{
    $('#zoomOut').addClass('disabled')
  }
}

function resetZoom(){
  x = zooms;
  if(zooms >= 0){
    for(i=1;i<=x;i++){
      zoomOut()
    }
  }else{
    for(i=-1;i>=x;i--){
      zoomIn()
    }
  }
}
</script>

<a hidden="hidden" id="productUrl" href="/products/${ product.getId() }"></a>

<div class="big-title">
	<c:out value="${ product.getFilename() }"></c:out>
</div>
<hr>
<nav aria-label="breadcrumb">
	<ol class="breadcrumb" id="breadcrumb">
		<!-- Autogenerated on productGraphics.js -->
	</ol>
</nav>

<div class="row no-gutters">
	<div id="graphCol" class="col-11">
		<div id="zoomer" class="zoomer">
			<div class="zoom-buttons">
				<div class="btn-group" id="zoom-buttons">
					<div id="zoomIn" class="btn btn-outline-secondary"
						onclick="zoomIn()"><i class="fas fa-plus"></i></div>
					<div id="zoomReset" class="btn btn-outline-secondary"
						onclick="resetZoom()"><i class="fas fa-expand-arrows-alt"></i></div>
					<div id="zoomOut" class="btn btn-outline-secondary disabled"
						onclick="zoomOut()"><i class="fas fa-minus"></i></div>
				</div>
				<div id="detailed-graphic-help" class="btn btn-outline-info">
					<i class="fas fa-question"></i></div>
			</div>
			<div id="detailedGraphic"></div>
		</div>
	</div>
	<div id="configCol" class="col-1 mt-5">
		<div class="row align-items-center no-gutters">
			<div class="col-1">
				<div class="vl">
					<div id="toggleButton" class="btn btn-outline-secondary">
						<i id="toggleButton-fa" class="fas fa-angle-left"></i>
					</div>
				</div>
			</div>
			<div class="col-11">
				<div id="productConfiguration" class="scrollable"
					style="display: none;">
					<div class="big-title">
						<spring:message code="domain.product.configuration"></spring:message>
					</div>
					<hr>
					<div>
						<div id="productConfig"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Configuration's JS -->
<script>             		
$(document).ready(function(){
	
    var clickFunction = function(event,target){
		var selectedId = target.node.id;
	       				
		// If selected, change sunburst graphic dynamicaly
		if(target.node.original.type == "selected"){
			sunburstGoTo(selectedId);
		}
	}
    
    var data = ${ configData }
       			
    createJstree(data,'productConfig',clickFunction);
    
 	// Toggle listener
	$('#toggleButton').click(function(){
		
		$('.jstree-anchor').popover('dispose')

	    var graph = document.getElementById("graphCol");
	    var config = document.getElementById("configCol");
	
	    if($("#productConfiguration").is(":hidden")){
	      $("#productConfiguration").show();
	      config.classList = "col-12 col-md-4";
	      graph.classList = "d-none d-md-block col-md-8";
	      $('#toggleButton-fa').removeClass("fa-angle-left").addClass("fa-angle-right");
	    }else{
	      $("#productConfiguration").hide();
	      config.classList = "col-1 mt-5";
	      graph.classList = "col-11";
	      $('#toggleButton-fa').removeClass("fa-angle-right").addClass("fa-angle-left");
	    }
	
	  })
       			
});
</script>

<!-- Sunburst chart's JS -->
<script>
	$(document).ready(function(){
		
		var clickFunction = function(){
			
			// get the drilldown path and convert it to a string
		    var path = chart.getDrilldownPath();

		    $('#breadcrumb').html("");
		    for(i = 0; i < path.length; i++){

		      if( i == path.length - 1){
		        $('#breadcrumb').append("<li class='breadcrumb-item active'>"+ path[i].get("name") +"</li>")
		      }else{
		        $('#breadcrumb').append("<li class='breadcrumb-item'><a href='#' onclick=\"sunburstGoTo('"+path[i].get("id") +"')\">"+ path[i].get("name") +"</a></li>")
		      }


		    }

		    if(path.length == 1){
		      // Root
		      chartLabel.text(calculate(selectedVp))
		    }else{
		    	chartLabel.text(calculate(path[path.length - 1].get("value")));
		    }
		}
		
		var data = ${data}
		
		chart = createSunburstChart(data,clickFunction);
		
		// set the container id
		chart.container("detailedGraphic");
	
		// initiate drawing the chart
		chart.draw();
		
		
		// Help tooltip
		
		$('#detailed-graphic-help').click(function(){
			$('#detailedGraphic').popover('dispose')
			
			$('#detailedGraphic').popover({
				animation: true,
				html: true,
				placement: "right",
				trigger: "manual",
				title: getString("tour.detailedgraphic.title"),
				content: getString("tour.detailedgraphic.content")
			});
			
			$('#detailedGraphic').popover('show')
		});
		
		$('#detailedGraphic').click(function(){
			$('#detailedGraphic').popover('dispose')
		})
	})
</script>
